<?xml version="1.0" encoding="utf-8"?><Database Name="Storage" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=Storage;Integrated Security=True;Trust Server Certificate=True" SettingsObjectName="ADO18._12._2024.Part2.Properties.Settings" SettingsPropertyName="StorageConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Informations" Member="Informations">
    <Type Name="Informations">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TypeProductId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateSupply" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SuppliersId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="Products_Informations" Member="Products" ThisKey="ProductId" OtherKey="Id" Type="Products" IsForeignKey="true" />
      <Association Name="Suppliers_Informations" Member="Suppliers" ThisKey="SuppliersId" OtherKey="Id" Type="Suppliers" IsForeignKey="true" />
      <Association Name="TypeProducts_Informations" Member="TypeProducts" ThisKey="TypeProductId" OtherKey="Id" Type="TypeProducts" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Products">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="Products_Informations" Member="Informations" ThisKey="Id" OtherKey="ProductId" Type="Informations" />
    </Type>
  </Table>
  <Table Name="dbo.Suppliers" Member="Suppliers">
    <Type Name="Suppliers">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="Suppliers_Informations" Member="Informations" ThisKey="Id" OtherKey="SuppliersId" Type="Informations" />
    </Type>
  </Table>
  <Table Name="dbo.TypeProducts" Member="TypeProducts">
    <Type Name="TypeProducts">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="TypeProducts_Informations" Member="Informations" ThisKey="Id" OtherKey="TypeProductId" Type="Informations" />
    </Type>
  </Table>
</Database>